
export const colombianCities = [
    "Bogotá",
    "Medellín",
    "Cali",
    "Barranquilla",
    "Cartagena",
    "Cúcuta",
    "Bucaramanga",
    "Pereira",
    "Santa Marta",
    "Ibagué",
    "Pasto",
    "Manizales",
    "Neiva",
    "Villavicencio",
    "Valledupar",
    "Montería",
    "Armenia",
    "Popayán",
    "Sincelejo",
    "Tunja",
    "Riohacha",
    "Florencia",
    "Quibdó",
    "Yopal",
    "Mocoa",
    "Arauca",
    "San José del Guaviare",
    "Leticia",
    "Inírida",
    "Mitú",
    "Puerto Carreño",
    "San Andrés"
];
