
export const colombianCities = [
    "Abejorral",
    "Abriaquí",
    "Acacías",
    "Aipe",
    "Albán (Cundinamarca)",
    "Albán (Nariño)",
    "Alcalá",
    "Alejandría",
    "Algeciras",
    "Almaguer",
    "Almeida",
    "Alvarado",
    "Amagá",
    "Amalfi",
    "Anapoima",
    "Ancuya",
    "Andalucía",
    "Andes",
    "Angelópolis",
    "Angostura",
    "Anolaima",
    "Anorí",
    "Anserma",
    "Ansermanuevo",
    "Anzá",
    "Apartadó",
    "Apía",
    "Apulo",
    "Aquitania",
    "Aracataca",
    "Aranzazu",
    "Aratoca",
    "Arauca",
    "Arauquita",
    "Arbeláez",
    "Arboleda",
    "Arboledas",
    "Arcabuco",
    "Argelia (Antioquia)",
    "Argelia (Cauca)",
    "Argelia (Valle del Cauca)",
    "Ariguaní",
    "Arjona",
    "Armenia",
    "Armero",
    "Ataco",
    "Ayapel",
    "Bagadó",
    "Bahía Solano",
    "Bajo Baudó",
    "Balboa (Cauca)",
    "Balboa (Risaralda)",
    "Baranoa",
    "Baraya",
    "Barbacoas",
    "Barbosa (Antioquia)",
    "Barbosa (Santander)",
    "Barichara",
    "Barranca de Upía",
    "Barrancabermeja",
    "Barrancas",
    "Barranco de Loba",
    "Barranquilla",
    "Becerril",
    "Belalcázar",
    "Belén (Boyacá)",
    "Belén (Nariño)",
    "Belén de Umbría",
    "Bello",
    "Belmira",
    "Berbeo",
    "Betania",
    "Betéitiva",
    "Betulia (Antioquia)",
    "Betulia (Santander)",
    "Bituima",
    "Boavita",
    "Bochalema",
    "Bogotá",
    "Bojacá",
    "Bolívar (Cauca)",
    "Bolívar (Santander)",
    "Bolívar (Valle del Cauca)",
    "Bosconia",
    "Boyacá",
    "Briceño (Antioquia)",
    "Briceño (Boyacá)",
    "Bucaramanga",
    "Bucarasica",
    "Buenaventura",
    "Buenavista (Boyacá)",
    "Buenavista (Córdoba)",
    "Buenavista (Quindío)",
    "Buenavista (Sucre)",
    "Buenos Aires",
    "Buesaco",
    "Buga",
    "Bugalagrande",
    "Buriticá",
    "Busbanzá",
    "Cabrera (Cundinamarca)",
    "Cabrera (Santander)",
    "Cabuyaro",
    "Cáceres",
    "Cachipay",
    "Cáchira",
    "Cácota",
    "Caicedo",
    "Caicedonia",
    "Caimito",
    "Cajamarca",
    "Cajibío",
    "Cajicá",
    "Calamar (Bolívar)",
    "Calamar (Guaviare)",
    "Calarcá",
    "Caldas (Antioquia)",
    "Caldas (Boyacá)",
    "Cali",
    "Calima",
    "California",
    "Caloto",
    "Campamento",
    "Campo de la Cruz",
    "Campoalegre",
    "Campohermoso",
    "Canalete",
    "Candelaria (Atlántico)",
    "Candelaria (Valle del Cauca)",
    "Cantagallo",
    "Caparrapí",
    "Capitanejo",
    "Caquetania",
    "Cáqueza",
    "Caracolí",
    "Caramanta",
    "Carcasí",
    "Carepa",
    "Carmen de Apicalá",
    "Carmen de Carupa",
    "Carmen del Darién",
    "Cartagena de Indias",
    "Cartagena del Chairá",
    "Cartago",
    "Carurú",
    "Casabianca",
    "Castilla la Nueva",
    "Caucasia",
    "Cepitá",
    "Cereté",
    "Cerinza",
    "Cerrito",
    "Cerro San Antonio",
    "Chachagüí",
    "Chaguaní",
    "Chalán",
    "Chameza",
    "Chaparral",
    "Charalá",
    "Charta",
    "Chía",
    "Chigorodó",
    "Chima (Córdoba)",
    "Chima (Santander)",
    "Chimá",
    "Chimichagua",
    "Chinácota",
    "Chinavita",
    "Chinchiná",
    "Chinú",
    "Chipaque",
    "Chipatá",
    "Chiquinquirá",
    "Chíquiza",
    "Chiriguaná",
    "Chiscas",
    "Chita",
    "Chitagá",
    "Chitaráque",
    "Chivatá",
    "Chivor",
    "Choachí",
    "Chocontá",
    "Cicuco",
    "Ciénaga",
    "Ciénaga de Oro",
    "Cimitarra",
    "Circasia",
    "Cisneros",
    "Ciudad Bolívar",
    "Clemencia",
    "Cocorná",
    "Coello",
    "Cofania",
    "Cogua",
    "Colombia",
    "Colón (Nariño)",
    "Colón (Putumayo)",
    "Coloso",
    "Cómbita",
    "Concepción (Antioquia)",
    "Concepción (Santander)",
    "Concordia (Antioquia)",
    "Concordia (Magdalena)",
    "Condoto",
    "Confines",
    "Consacá",
    "Contadero",
    "Contratación",
    "Copacabana",
    "Coper",
    "Córdoba",
    "Corinto",
    "Coromoro",
    "Corozal",
    "Corrales",
    "Cota",
    "Cotorra",
    "Covarachía",
    "Coveñas",
    "Coyaima",
    "Cravo Norte",
    "Cuaspud",
    "Cubarral",
    "Cubará",
    "Cucunubá",
    "Cúcuta",
    "Cucutilla",
    "Cuítiva",
    "Cumaral",
    "Cumaribo",
    "Cumbal",
    "Cumbitara",
    "Cunday",
    "Curillo",
    "Curití",
    "Curumaní",
    "Dabeiba",
    "Dagua",
    "Dibulla",
    "Distracción",
    "Dolores",
    "Donmatías",
    "Dosquebradas",
    "Duitama",
    "Durania",
    "Ebéjico",
    "El Águila",
    "El Bagre",
    "El Banco",
    "El Cairo",
    "El Calvario",
    "El Cantón del San Pablo",
    "El Carmen de Atrato",
    "El Carmen de Bolívar",
    "El Carmen de Chucurí",
    "El Carmen de Viboral",
    "El Castillo",
    "El Cerrito",
    "El Charco",
    "El Cocuy",
    "El Colegio",
    "El Copey",
    "El Doncello",
    "El Dorado",
    "El Dovio",
    "El Espino",
    "El Guacamayo",
    "El Guamo (Bolívar)",
    "El Guamo (Tolima)",
    "El Litoral del San Juan",
    "El Molino",
    "El Paso",
    "El Paujil",
    "El Peñol",
    "El Peñón (Bolívar)",
    "El Peñón (Cundinamarca)",
    "El Peñón (Santander)",
    "El Piñón",
    "El Playón",
    "El Retén",
    "El Retorno",
    "El Rosal",
    "El Santuario",
    "El Tablón de Gómez",
    "El Tambo (Cauca)",
    "El Tambo (Nariño)",
    "El Tarra",
    "El Zulia",
    "Encino",
    "Enciso",
    "Entrerríos",
    "Envigado",
    "Espinal",
    "Facatativá",
    "Falan",
    "Filadelfia",
    "Filandia",
    "Firavitoba",
    "Flandes",
    "Florencia (Caquetá)",
    "Florencia (Cauca)",
    "Floresta",
    "Florida",
    "Floridablanca",
    "Fomeque",
    "Fonseca",
    "Fortul",
    "Fosca",
    "Francisco Pizarro",
    "Fredonia",
    "Fresno",
    "Frontino",
    "Fuente de Oro",
    "Fundación",
    "Funes",
    "Funza",
    "Fúquene",
    "Fusagasugá",
    "Gachalá",
    "Gachancipá",
    "Gachantivá",
    "Gachetá",
    "Galán",
    "Galapa",
    "Galeras",
    "Gama",
    "Gamarra",
    "Gámbita",
    "Garagoa",
    "Garzón",
    "Génova",
    "Gigante",
    "Ginebra",
    "Giraldo",
    "Girardot",
    "Girardota",
    "Girón",
    "Gómez Plata",
    "González",
    "Gramalote",
    "Granada (Antioquia)",
    "Granada (Cundinamarca)",
    "Granada (Meta)",
    "Guaca",
    "Guacamayas",
    "Guacarí",
    "Guachené",
    "Guachetá",
    "Guadalajara de Buga",
    "Guadalupe (Antioquia)",
    "Guadalupe (Huila)",
    "Guadalupe (Santander)",
    "Guaduas",
    "Guaitarilla",
    "Gualmatán",
    "Guamal (Magdalena)",
    "Guamal (Meta)",
    "Guamo",
    "Guapí",
    "Guapotá",
    "Guaranda",
    "Guarne",
    "Guasca",
    "Guatapé",
    "Guataquí",
    "Guatavita",
    "Guateque",
    "Guática",
    "Guavatá",
    "Guayabal de Síquima",
    "Guayabetal",
    "Guayatá",
    "Güepsa",
    "Güicán",
    "Gutiérrez",
    "Hacarí",
    "Hatillo de Loba",
    "Hato",
    "Hato Corozal",
    "Hatonuevo",
    "Heliconia",
    "Herrán",
    "Herveo",
    "Hispania",
    "Hobo",
    "Honda",
    "Ibagué",
    "Icononzo",
    "Iles",
    "Imués",
    "Inírida",
    "Ipiales",
    "Iquira",
    "Isnos",
    "Istmina",
    "Itagüí",
    "Ituango",
    "Iza",
    "Jambaló",
    "Jamundí",
    "Jardín",
    "Jenesano",
    "Jericó (Antioquia)",
    "Jericó (Boyacá)",
    "Jerusalén",
    "Jesús María",
    "Jordán",
    "Juan de Acosta",
    "Junín",
    "Juradó",
    "La Apartada",
    "La Argentina",
    "La Belleza",
    "La Calera",
    "La Capilla",
    "La Ceja",
    "La Celia",
    "La Cruz",
    "La Cumbre",
    "La Dorada",
    "La Esperanza",
    "La Estrella",
    "La Florida",
    "La Gloria",
    "La Jagua de Ibirico",
    "La Jagua del Pilar",
    "La Llanada",
    "La Macarena",
    "La Merced",
    "La Mesa",
    "La Montañita",
    "La Palma",
    "La Paz (Cesar)",
    "La Paz (Santander)",
    "La Peña",
    "La Pinta",
    "La Pintada",
    "La Plata",
    "La Primavera",
    "La Salina",
    "La Sierra",
    "La Tebaida",
    "La Tola",
    "La Uvita",
    "La Unión (Antioquia)",
    "La Unión (Nariño)",
    "La Unión (Sucre)",
    "La Unión (Valle del Cauca)",
    "La Uribe",
    "La Vega (Cauca)",
    "La Vega (Cundinamarca)",
    "La Victoria (Amazonas)",
    "La Victoria (Boyacá)",
    "La Victoria (Valle del Cauca)",
    "La Virginia",
    "Labateca",
    "Labranzagrande",
    "Landázuri",
    "Lebríja",
    "Leiva",
    "Lejanías",
    "Lenguazaque",
    "Lérida",
    "Leticia",
    "Líbano",
    "Liborina",
    "Linares",
    "Lloró",
    "López de Micay",
    "Lorica",
    "Los Andes",
    "Los Córdobas",
    "Los Palmitos",
    "Los Patios",
    "Los Santos",
    "Lourdes",
    "Luruaco",
    "Macanal",
    "Macaravita",
    "Maceo",
    "Machetá",
    "Madrid",
    "Magangué",
    "Magüí Payán",
    "Mahates",
    "Maicao",
    "Majagual",
    "Málaga",
    "Malambo",
    "Mallama",
    "Manatí",
    "Manaure",
    "Manaure Balcón del Cesar",
    "Maní",
    "Manizales",
    "Manta",
    "Manzanares",
    "Mapiripán",
    "Margarita",
    "María La Baja",
    "Marinilla",
    "Maripí",
    "Mariquita",
    "Marmato",
    "Marquetalia",
    "Marsella",
    "Marulanda",
    "Matanza",
    "Medellín",
    "Medina",
    "Medio Atrato",
    "Medio Baudó",
    "Medio San Juan",
    "Melgar",
    "Mercaderes",
    "Mesetas",
    "Milán",
    "Miraflores (Boyacá)",
    "Miraflores (Guaviare)",
    "Miranda",
    "Mistrató",
    "Mitú",
    "Mocoa",
    "Mogotes",
    "Molagavita",
    "Momil",
    "Mompós",
    "Mongua",
    "Monguí",
    "Moniquirá",
    "Montebello",
    "Montecristo",
    "Montelíbano",
    "Montenegro",
    "Montería",
    "Monterrey",
    "Moñitos",
    "Morales (Bolívar)",
    "Morales (Cauca)",
    "Morelia",
    "Morroa",
    "Mosquera (Cundinamarca)",
    "Mosquera (Nariño)",
    "Motavita",
    "Murillo",
    "Murindó",
    "Mutatá",
    "Mutiscua",
    "Muzo",
    "Nariño (Antioquia)",
    "Nariño (Cundinamarca)",
    "Nariño (Nariño)",
    "Nátaga",
    "Natagaima",
    "Nechí",
    "Necoclí",
    "Neira",
    "Neiva",
    "Nemocón",
    "Nilo",
    "Nimaima",
    "Nobsa",
    "Nocaima",
    "Norcasia",
    "Nóvita",
    "Nueva Granada",
    "Nuevo Colón",
    "Nunchía",
    "Nuquí",
    "Obando",
    "Ocamonte",
    "Ocaña",
    "Oiba",
    "Oicatá",
    "Olaya",
    "Olaya Herrera",
    "Onzaga",
    "Oporapa",
    "Orito",
    "Orocué",
    "Ortega",
    "Ospina",
    "Otanche",
    "Ovejas",
    "Pachavita",
    "Pacho",
    "Pácora",
    "Padilla",
    "Páez (Boyacá)",
    "Páez (Cauca)",
    "Paicol",
    "Pailitas",
    "Paime",
    "Paipa",
    "Pajarito",
    "Palermo",
    "Palestina (Caldas)",
    "Palestina (Huila)",
    "Palmar",
    "Palmar de Varela",
    "Palmas del Socorro",
    "Palmira",
    "Palmito",
    "Pamplona",
    "Pamplonita",
    "Pandi",
    "Panqueba",
    "Páramo",
    "Paratebueno",
    "Pasca",
    "Pasto",
    "Patía",
    "Pauna",
    "Paya",
    "Paz de Ariporo",
    "Paz de Río",
    "Pedraza",
    "Pelaya",
    "Pensilvania",
    "Peque",
    "Pereira",
    "Pesca",
    "Piamonte",
    "Pie de Cuesta",
    "Piedecuesta",
    "Piedras",
    "Piendamó",
    "Pijiño del Carmen",
    "Pijao",
    "Pinchote",
    "Pinillos",
    "Piojó",
    "Pisba",
    "Pital",
    "Pitalito",
    "Pivijay",
    "Planadas",
    "Planeta Rica",
    "Plato",
    "Policarpa",
    "Polonuevo",
    "Ponedera",
    "Popayán",
    "Pore",
    "Potosí",
    "Pradera",
    "Prado",
    "Providencia (Nariño)",
    "Providencia (San Andrés y Providencia)",
    "Pueblo Bello",
    "Pueblo Nuevo",
    "Pueblo Rico",
    "Pueblorrico",
    "Puebloviejo",
    "Puente Nacional",
    "Puerres",
    "Puerto Asís",
    "Puerto Berrío",
    "Puerto Boyacá",
    "Puerto Caicedo",
    "Puerto Carreño",
    "Puerto Colombia",
    "Puerto Concordia",
    "Puerto Escondido",
    "Puerto Gaitán",
    "Puerto Guzmán",
    "Puerto Leguízamo",
    "Puerto Libertador",
    "Puerto Lleras",
    "Puerto López",
    "Puerto Nare",
    "Puerto Nariño",
    "Puerto Parra",
    "Puerto Rico (Caquetá)",
    "Puerto Rico (Meta)",
    "Puerto Rondón",
    "Puerto Salgar",
    "Puerto Santander",
    "Puerto Tejada",
    "Puerto Triunfo",
    "Puerto Wilches",
    "Pulí",
    "Pupiales",
    "Puracé",
    "Purificación",
    "Purísima",
    "Quebradanegra",
    "Quetame",
    "Quibdó",
    "Quimbaya",
    "Quinchía",
    "Quípama",
    "Quipile",
    "Ragonvalia",
    "Ramiriquí",
    "Ráquira",
    "Recetor",
    "Regidor",
    "Remedios",
    "Remolino",
    "Repelón",
    "Restrepo (Meta)",
    "Restrepo (Valle del Cauca)",
    "Retiro",
    "Ricaurte (Cundinamarca)",
    "Ricaurte (Nariño)",
    "Río de Oro",
    "Río Frío",
    "Río Iró",
    "Río Quito",
    "Río Viejo",
    "Rioblanco",
    "Riohacha",
    "Rionegro (Antioquia)",
    "Rionegro (Santander)",
    "Riosucio (Caldas)",
    "Riosucio (Chocó)",
    "Risaralda",
    "Rivera",
    "Roberto Payán",
    "Roldanillo",
    "Roncesvalles",
    "Rondón",
    "Rosas",
    "Rovira",
    "Sabanagrande",
    "Sabana de Torres",
    "Sabanalarga (Antioquia)",
    "Sabanalarga (Atlántico)",
    "Sabanalarga (Casanare)",
    "Sabaneta",
    "Saboyá",
    "Sácama",
    "Sáchica",
    "Sahagún",
    "Saladoblanco",
    "Salamina (Caldas)",
    "Salamina (Magdalena)",
    "Salazar",
    "Saldaña",
    "Salento",
    "Salgar",
    "Samacá",
    "Samaná",
    "Samaniego",
    "Sampués",
    "San Agustín",
    "San Alberto",
    "San Andrés (San Andrés y Providencia)",
    "San Andrés (Santander)",
    "San Andrés de Cuerquia",
    "San Andrés de Sotavento",
    "San Antero",
    "San Antonio",
    "San Antonio del Tequendama",
    "San Benito",
    "San Benito Abad",
    "San Bernardo (Cundinamarca)",
    "San Bernardo (Nariño)",
    "San Bernardo del Viento",
    "San Calixto",
    "San Carlos (Antioquia)",
    "San Carlos (Córdoba)",
    "San Carlos de Guaroa",
    "San Cayetano (Cundinamarca)",
    "San Cayetano (Norte de Santander)",
    "San Cristóbal",
    "San Diego",
    "San Eduardo",
    "San Estanislao",
    "San Fernando",
    "San Francisco (Antioquia)",
    "San Francisco (Cundinamarca)",
    "San Francisco (Putumayo)",
    "San Gil",
    "San Jacinto",
    "San Jacinto del Cauca",
    "San Jerónimo",
    "San Joaquín",
    "San José (Caldas)",
    "San José de la Montaña",
    "San José de Miranda",
    "San José de Pare",
    "San José del Fragua",
    "San José del Guaviare",
    "San José del Palmar",
    "San Juan de Arama",
    "San Juan de Betulia",
    "San Juan de Rioseco",
    "San Juan del Cesar",
    "San Juan Nepomuceno",
    "San Juanito",
    "San Lorenzo",
    "San Luis",
    "San Luis de Gaceno",
    "San Luis de Palenque",
    "San Marcos",
    "San Martín (Cesar)",
    "San Martín (Meta)",
    "San Martín de Loba",
    "San Mateo",
    "San Miguel (Putumayo)",
    "San Miguel (Santander)",
    "San Miguel de Sema",
    "San Onofre",
    "San Pablo (Bolívar)",
    "San Pablo (Nariño)",
    "San Pablo de Borbur",
    "San Pedro (Antioquia)",
    "San Pedro (Sucre)",
    "San Pedro (Valle del Cauca)",
    "San Pedro de Cartago",
    "San Pedro de Urabá",
    "San Pelayo",
    "San Rafael",
    "San Roque",
    "San Sebastián",
    "San Sebastián de Buenavista",
    "San Vicente de Chucurí",
    "San Vicente del Caguán",
    "San Zenón",
    "Sandoná",
    "Santa Ana",
    "Santa Bárbara (Antioquia)",
    "Santa Bárbara (Nariño)",
    "Santa Bárbara (Santander)",
    "Santa Catalina",
    "Santa Fe de Antioquia",
    "Santa Genoveva de Docorodó",
    "Santa Helena del Opón",
    "Santa Isabel",
    "Santa Lucía",
    "Santa María (Boyacá)",
    "Santa María (Huila)",
    "Santa Marta",
    "Santa Rosa (Bolívar)",
    "Santa Rosa (Cauca)",
    "Santa Rosa de Cabal",
    "Santa Rosa de Osos",
    "Santa Rosa de Viterbo",
    "Santa Rosa del Sur",
    "Santa Sofía",
    "Santana",
    "Santander de Quilichao",
    "Santiago (Norte de Santander)",
    "Santiago (Putumayo)",
    "Santo Domingo",
    "Santo Tomás",
    "Santuario",
    "Sapuyes",
    "Saravena",
    "Sardinata",
    "Sasaima",
    "Sativanorte",
    "Sativasur",
    "Segovia",
    "Sesquilé",
    "Sevilla",
    "Siachoque",
    "Sibaté",
    "Sibundoy",
    "Silos",
    "Silvania",
    "Silvia",
    "Simacota",
    "Simijaca",
    "Simití",
    "Sincelejo",
    "Sincé",
    "Sipí",
    "Sitionuevo",
    "Soacha",
    "Soatá",
    "Socha",
    "Socorro",
    "Socotá",
    "Sogamoso",
    "Solano",
    "Soledad",
    "Solita",
    "Somondoco",
    "Sonsón",
    "Sopetrán",
    "Soplaviento",
    "Sopó",
    "Sora",
    "Soracá",
    "Sotaquirá",
    "Sotara",
    "Suaita",
    "Suan",
    "Suárez (Cauca)",
    "Suárez (Tolima)",
    "Suaza",
    "Subachoque",
    "Sucre (Cauca)",
    "Sucre (Santander)",
    "Sucre (Sucre)",
    "Suesca",
    "Supatá",
    "Supía",
    "Suratá",
    "Susa",
    "Sutacachán",
    "Sutamarchán",
    "Sutatenza",
    "Sutatausa",
    "Tabio",
    "Tadó",
    "Talaigua Nuevo",
    "Tamalameque",
    "Támara",
    "Tame",
    "Támesis",
    "Taminango",
    "Tangua",
    "Tarazá",
    "Tarqui",
    "Tarso",
    "Tasco",
    "Tauramena",
    "Tausa",
    "Tello",
    "Tena",
    "Tenerife",
    "Tenjo",
    "Tenza",
    "Teorama",
    "Teruel",
    "Tesalia",
    "Tibacuy",
    "Tibaná",
    "Tibasosa",
    "Tibirita",
    "Tibú",
    "Tierralta",
    "Timaná",
    "Timbío",
    "Timbiquí",
    "Tinjacá",
    "Tipacoque",
    "Tiquisio",
    "Titiribí",
    "Toca",
    "Tocaima",
    "Tocancipá",
    "Togüí",
    "Toledo (Antioquia)",
    "Toledo (Norte de Santander)",
    "Tolú",
    "Tolú Viejo",
    "Tona",
    "Tópaga",
    "Topaipí",
    "Toribío",
    "Toro",
    "Tota",
    "Totoró",
    "Trinidad",
    "Trujillo",
    "Tubará",
    "Tuluá",
    "Tumaco",
    "Tunja",
    "Tununguá",
    "Túquerres",
    "Turbaco",
    "Turbaná",
    "Turbo",
    "Turmequé",
    "Tuta",
    "Tutasá",
    "Ubalá",
    "Ubaque",
    "Ulloa",
    "Úmbita",
    "Une",
    "Unguía",
    "Unión Panamericana",
    "Uramita",
    "Uribe",
    "Uribia",
    "Urrao",
    "Urumita",
    "Usme",
    "Útica",
    "Valdivia",
    "Valencia",
    "Valparaíso (Antioquia)",
    "Valparaíso (Caquetá)",
    "Vegachí",
    "Vélez",
    "Venadillo",
    "Venecia (Antioquia)",
    "Venecia (Cundinamarca)",
    "Ventaquemada",
    "Vergara",
    "Versalles",
    "Vetas",
    "Vianí",
    "Victoria",
    "Vigía del Fuerte",
    "Vijes",
    "Villa de Leyva",
    "Villa del Rosario",
    "Villa Rica",
    "Villagarzón",
    "Villagómez",
    "Villahermosa",
    "Villamaría",
    "Villanueva (Bolívar)",
    "Villanueva (Casanare)",
    "Villanueva (La Guajira)",
    "Villanueva (Santander)",
    "Villapinzón",
    "Villarrica",
    "Villavicencio",
    "Villeta",
    "Viotá",
    "Viracachá",
    "Vista Hermosa",
    "Viterbo",
    "Yacopí",
    "Yacuanquer",
    "Yaguará",
    "Yalí",
    "Yarumal",
    "Yolombó",
    "Yondó",
    "Yopal",
    "Yotoco",
    "Yumbo",
    "Zambrano",
    "Zapatoca",
    "Zapayán",
    "Zaragoza",
    "Zarzal",
    "Zetaquira",
    "Zipacón",
    "Zipaquirá",
];
